// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3sGlxtYmuO68wOgfqOK0SLFEoptKQLqs',
    appId: '1:983848821035:web:9925836baad2b3bca2656e',
    messagingSenderId: '983848821035',
    projectId: 'makc-auto',
    authDomain: 'makc-auto.firebaseapp.com',
    storageBucket: 'makc-auto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSG58X1CRs1X_Sj8PdhFOX6jANYQdnJEk',
    appId: '1:983848821035:android:9934fc5bb91cd60ca2656e',
    messagingSenderId: '983848821035',
    projectId: 'makc-auto',
    storageBucket: 'makc-auto.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVGKTwsRCoFEs_enPEbZsUC6fQP6SgLU',
    appId: '1:983848821035:ios:a7e1e1a5e94e0d4fa2656e',
    messagingSenderId: '983848821035',
    projectId: 'makc-auto',
    storageBucket: 'makc-auto.firebasestorage.app',
    iosBundleId: 'com.makc.agsolutions',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGVGKTwsRCoFEs_enPEbZsUC6fQP6SgLU',
    appId: '1:983848821035:ios:30edc77a6a39302aa2656e',
    messagingSenderId: '983848821035',
    projectId: 'makc-auto',
    storageBucket: 'makc-auto.firebasestorage.app',
    iosBundleId: 'com.example.makc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3sGlxtYmuO68wOgfqOK0SLFEoptKQLqs',
    appId: '1:983848821035:web:e4adb48febd9cc50a2656e',
    messagingSenderId: '983848821035',
    projectId: 'makc-auto',
    authDomain: 'makc-auto.firebaseapp.com',
    storageBucket: 'makc-auto.firebasestorage.app',
  );
}
